// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo3AUyv0Ornm4SGbJW1squntTMVxmOhbI',
    appId: '1:800268154683:web:595059583ce691597ee91e',
    messagingSenderId: '800268154683',
    projectId: 'whatsapp-clone-ac0bb',
    authDomain: 'whatsapp-clone-ac0bb.firebaseapp.com',
    storageBucket: 'whatsapp-clone-ac0bb.appspot.com',
    measurementId: 'G-P95WXHZC1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkRLj_darutODVIKiHouN1kWj_EnRg8Eo',
    appId: '1:800268154683:android:17787f00f2cd5fec7ee91e',
    messagingSenderId: '800268154683',
    projectId: 'whatsapp-clone-ac0bb',
    storageBucket: 'whatsapp-clone-ac0bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsx4M21upd_ATVkQaAXZphvz_ro3qFd90',
    appId: '1:800268154683:ios:dca974828602097f7ee91e',
    messagingSenderId: '800268154683',
    projectId: 'whatsapp-clone-ac0bb',
    storageBucket: 'whatsapp-clone-ac0bb.appspot.com',
    iosClientId: '800268154683-m6fuh7lgqt08ed0ja9q21hi93h37knpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
